name: Publish ❯ Site
# Generates and publishes site

on:
  workflow_dispatch:

  push:
    branches: ["latest"]

concurrency:
  group: publish-site-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and Publish Site
    runs-on: ${{ vars.PREFERRED_OS }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Erlang & Elixir
        id: beam-versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ vars.PREFERRED_ELIXIR }}
          otp-version: ${{ vars.PREFERRED_OTP }}

      - name: Restore mix dependency installation cache
        id: mix-deps-get-cache
        uses: actions/cache@v4
        with:
          path: deps
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-mix-deps-get-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install mix dependencies
        if: steps.mix-deps-get-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Restore mix dependency compilation cache
        id: mix-deps-compile-cache
        uses: actions/cache@v4
        with:
          path: _build
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-mix-deps-compile-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Compile mix dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Build site
        run: mix build

      - name: Upload built static site to Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./site"

      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
